# This is a basic workflow to help you get started with Actions

name: CI/CD

on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@master
      - name: Init
        uses: onichandame/python-test-action@master
      - name: Peewee check
        run: |
          pip install peewee
      
         # Runs a set of commands using the runners shell
      - name: integration
        run: |
          python -m unittest Librabobus/Tests/IntTests/integration_tests.py
          python -m unittest Librabobus/Tests/IntTests/integration_tests_mock.py
